CREATE TABLE IF NOT EXISTS inactive_cards (
    id SERIAL PRIMARY KEY,
    card_pk INT NOT NULL,
    user_id INT NOT NULL,
    card_updated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
