CREATE TABLE IF NOT EXISTS facts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_pk INTEGER NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
    fact TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);