kind: pipeline
type: docker
name: default

steps:
  - name: build-frontend
    image: plugins/docker
    settings:
      repo: nsavage/zettelkasten-front
      context: ./zettelkasten-front
      dockerfile: ./zettelkasten-front/Dockerfile
    when:
      event:
        - push