kind: pipeline
type: docker
name: default

steps:
  - name: build-frontend
    image: plugins/docker
    commands:
      - "docker build -t nsavage-zettelkasten -f ./zettelkasten-front/Dockerfile-frontend ."