version: '3'

services:
  frontend:
    build:
      context: ./zettelkasten-front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - stack.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - stack.env