version: '3'

services:
  frontend:
    build:
      context: ./zettelkasten-front
      dockerfile: Dockerfile
      args:
        REACT_APP_URL: ${REACT_APP_URL}
        REACT_APP_USERNAME: ${REACT_APP_USERNAME}
        REACT_APP_PASSWORD: ${REACT_APP_PASSWORD}
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_URL=${REACT_APP_URL}
      - REACT_APP_USERNAME=${REACT_APP_USERNAME}
      - REACT_APP_PASSWORD=${REACT_APP_PASSWORD}
    env_file:
      - stack.env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - stack.env