version: '3'

services:
  frontend:
    build:
      context: ./zettelkasten-front
      dockerfile: Dockerfile
      args:
        REACT_APP_URL: http://192.168.0.72:5000/api
    ports:
      - "3001:3000"
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env