version: '3'

services:
  frontend:
    image: nsavage/zettelgarden_frontend:latest
          #image: 192.168.0.97:50000/zettelkasten_frontend:latest
    ports:
      - "3001:3000"
    depends_on:
      - go_backend

  go_backend:
    image: nsavage/zettelgarden_go_backend:latest
      #image: 192.168.0.97:50000/zettelkasten_go_backend:latest
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"
    env_file:
      - zettel.env
  db:
    image: postgres
    env_file:
      - zettel.env
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zettelkasten"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
