version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - go_backend

  frontend:
    image: nsavage/zettelgarden_frontend:latest
    restart: always
    expose:
      - "3000"
    depends_on:
      - go_backend

  go_backend:
    image: nsavage/zettelgarden_go_backend:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    expose:
      - "8080" 
    env_file:
      - zettel.env
    volumes:
      - /var/log/zettel:/app/logs

  db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - zettel.env
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zettelkasten"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  mail-service:
    image: nsavage/zettelgarden_python_mail:latest
    restart: always
    expose:
      - "8081"
    env_file:
      - zettel.env
    volumes:
      - /var/log/zettel:/app/logs