version: "3"

services:
  frontend:
    build:
      context: ./zettelkasten-front
      dockerfile: Dockerfile
      args:
        VITE_URL: ${VITE_URL}
    image: nsavage/zettelgarden_frontend:latest
    ports:
      - "3001:3000"
    environment:
      - VITE_URL=${VITE_URL}

  go-backend:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    image: nsavage/zettelgarden_go_backend:latest
    ports:
      - "8080:8080"
    env_file:
      - .env

  mail-service:
    build:
      context: ./python-mail
      dockerfile: Dockerfile
    image: nsavage/zettelgarden_python_mail:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
