version: '3'

services:
  frontend:
    image: 192.168.0.129:50000/zettelkasten_frontend:latest  # Replace with your Docker Hub image path
    ports:
      - "3001:3000"  # Maps port 3000 on the host to port 3000 on the container
    depends_on:
      - backend

  backend:
    image: 192.168.0.129:50000/zettelkasten_backend:latest  # Replace with your Docker Hub image path
    ports:
      - "5000:5000"  # Maps port 5000 on the host to port 5000 on the container
    env_file:
      - zettel.env