name: Docker Compose Build

on [push]:

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ gitea.event_name }} event."
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Images with Compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push