name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'  # Adjust this to your Go version

    - name: Install dependencies
      run: |
        cd go-backend
        go mod download

    - name: Run tests
      run: |
        cd go-backend
        go test ./...
